const mongoose = require("mongoose");
const Ingredient = require("../models/ingredient");
const Provider = require("../models/provider");
const { connect } = require("../db/db_atlas");
const ingredients = [
  { name: "Surimi", allergic: "", price: 4, Ingredient: "" },
  { name: "Suplemento proteico", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Sopa de sobre, sin reconstituir",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Sopa de sobre maravilla", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Soja, seca, remojada, hervida",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Soja, seca, cruda", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Soja, germinada, en conserva",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Soja, frita", allergic: "", price: 4, Ingredient: "" },
  { name: "Soja, fresca", allergic: "", price: 4, Ingredient: "" },
  { name: "Sofrito", allergic: "", price: 4, Ingredient: "" },
  { name: "Soda", allergic: "", price: 4, Ingredient: "" },
  { name: "Sobrasada", allergic: "", price: 4, Ingredient: "" },
  { name: "Sobao", allergic: "", price: 4, Ingredient: "" },
  { name: "Sidra", allergic: "", price: 4, Ingredient: "" },
  { name: "Seta, plancha", allergic: "", price: 4, Ingredient: "" },
  { name: "Seta", allergic: "", price: 4, Ingredient: "" },
  { name: "Sesos, de ternera, crudos", allergic: "", price: 4, Ingredient: "" },
  { name: "Sesos, de cordero, crudos", allergic: "", price: 4, Ingredient: "" },
  { name: "Sesos, de cerdo, crudos", allergic: "", price: 4, Ingredient: "" },
  { name: "Sésamo, semilla", allergic: "", price: 4, Ingredient: "" },
  { name: "Sepia", allergic: "", price: 4, Ingredient: "" },
  { name: "Sémola de trigo, hervida", allergic: "", price: 4, Ingredient: "" },
  { name: "Sémola de trigo, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Semilla de lino", allergic: "", price: 4, Ingredient: "" },
  { name: "Seitán", allergic: "", price: 4, Ingredient: "" },
  { name: "Sargo, crudo", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Sardina, enlatada, en escabeche",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Sardina, enlatada, en aceite, escurrida",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Sardina, asada", allergic: "", price: 4, Ingredient: "" },
  { name: "Sardina", allergic: "", price: 4, Ingredient: "" },
  { name: "Sangría", allergic: "", price: 4, Ingredient: "" },
  { name: "Sandía", allergic: "", price: 4, Ingredient: "" },
  { name: "San jacobo, congelado", allergic: "", price: 4, Ingredient: "" },
  { name: "Salvado de trigo", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Salsa vinagreta, con aceite de oliva",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Salsa siciliana, picante", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa napolitana", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa de soja", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa de queso", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa carbonara", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa boloñesa", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa bechamel", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa barbacoa", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa al roquefort", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa al curry", allergic: "", price: 4, Ingredient: "" },
  { name: "Salsa agridulce", allergic: "", price: 4, Ingredient: "" },
  { name: "Salmonete", allergic: "", price: 4, Ingredient: "" },
  { name: "Salmón, plancha", allergic: "", price: 4, Ingredient: "" },
  { name: "Salmón ahumado", allergic: "", price: 4, Ingredient: "" },
  { name: "Salmón", allergic: "", price: 4, Ingredient: "" },
  { name: "Salema, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Salchichón", allergic: "", price: 4, Ingredient: "" },
  { name: "Salchicha, tipo viena", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Salchicha, tipo país, a la plancha",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: 'Salchicha, tipo "frankfurt"',
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Salchicha, fresca", allergic: "", price: 4, Ingredient: "" },
  { name: "Salchicha de pollo fresca", allergic: "", price: 4, Ingredient: "" },
  { name: "Salami", allergic: "", price: 4, Ingredient: "" },
  { name: "Sal yodada", allergic: "", price: 4, Ingredient: "" },
  { name: "Sal de mar", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Macedonia de frutas, conserva en su jugo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Magdalena", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Maíz, en mazorca, congelado, crudo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Maíz, en mazorca, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Mandarina", allergic: "", price: 4, Ingredient: "" },
  { name: "Mandarina, congelada", allergic: "", price: 4, Ingredient: "" },
  { name: "Mango, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Manteca", allergic: "", price: 4, Ingredient: "" },
  { name: "Mantequilla salada", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Mantequilla, baja en calorías",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Manzana", allergic: "", price: 4, Ingredient: "" },
  { name: "Margarina de maíz", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Margarina, baja en calorías",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Masa de hojaldre, cruda", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Mayonesa con aceite de girasol",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Mayonesa, aceite de oliva", allergic: "", price: 4, Ingredient: "" },
  { name: "Mayonesa, aceite de soja", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Mayonesa, baja en calorías",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Mejillon", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Mejillón, en conserva, al natural",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Mejillón, en escabeche", allergic: "", price: 4, Ingredient: "" },
  { name: "Mejillón, hervido", allergic: "", price: 4, Ingredient: "" },
  { name: "Melocotón", allergic: "", price: 4, Ingredient: "" },
  { name: "Melocotón en almíbar", allergic: "", price: 4, Ingredient: "" },
  { name: "Melocotón, desecado", allergic: "", price: 4, Ingredient: "" },
  { name: "Melón", allergic: "", price: 4, Ingredient: "" },
  { name: "Membrillo, crudo", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Menestra de verduras, congelada",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Menta, fresca", allergic: "", price: 4, Ingredient: "" },
  { name: "Merluza fresca", allergic: "", price: 4, Ingredient: "" },
  { name: "Merluza, congelada, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Merluza, rebozada, frita", allergic: "", price: 4, Ingredient: "" },
  { name: "Mermelada de albaricoque", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Mermelada de albaricoque y melocotón, baja en calorías",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Mermelada de ciruela", allergic: "", price: 4, Ingredient: "" },
  { name: "Mermelada de frambuesa", allergic: "", price: 4, Ingredient: "" },
  { name: "Mermelada de fresa", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Mermelada de fresa, baja en calorías",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Mermelada de grosella roja",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Mermelada de mora", allergic: "", price: 4, Ingredient: "" },
  { name: "Mermelada de naranja", allergic: "", price: 4, Ingredient: "" },
  { name: "Mero, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Mero, plancha", allergic: "", price: 4, Ingredient: "" },
  { name: "Miel", allergic: "", price: 4, Ingredient: "" },
  { name: "Mijo", allergic: "", price: 4, Ingredient: "" },
  { name: "Miso", allergic: "", price: 4, Ingredient: "" },
  { name: "Mojo picon", allergic: "", price: 4, Ingredient: "" },
  { name: "Molleja de cordero", allergic: "", price: 4, Ingredient: "" },
  { name: "Morcilla", allergic: "", price: 4, Ingredient: "" },
  { name: "Morcilla, frita", allergic: "", price: 4, Ingredient: "" },
  { name: "Mortadela", allergic: "", price: 4, Ingredient: "" },
  { name: "Mostaza", allergic: "", price: 4, Ingredient: "" },
  { name: "Mousse de chocolate", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Mousse de queso fresco, con frutas",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Mousse de queso fresco, desnatado, azucarado",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Mousse de queso fresco, desnatado, con frutas",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Mousse de yogur, con frutas",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Mousse de yogur, natural", allergic: "", price: 4, Ingredient: "" },
  { name: "Muesli", allergic: "", price: 4, Ingredient: "" },
  { name: "Mújol, al horno", allergic: "", price: 4, Ingredient: "" },
  { name: "Mújol, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Tabasco", allergic: "", price: 4, Ingredient: "" },
  { name: "Tapioca, hervida", allergic: "", price: 4, Ingredient: "" },
  { name: "Té, infusión, con leche", allergic: "", price: 4, Ingredient: "" },
  { name: "Tenca, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Tequila", allergic: "", price: 4, Ingredient: "" },
  { name: "Ternera, costilla, cruda", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Ternera, lomo, crudo, con grasa separable",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Ternera, parte s/e, asada", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Ternera, parte sin especificar, cruda, con grasa separable",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Ternera, solomillo, asado", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Ternera, solomillo, sin grasa, crudo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Tocino", allergic: "", price: 4, Ingredient: "" },
  { name: "Tofu", allergic: "", price: 4, Ingredient: "" },
  { name: "Tomate", allergic: "", price: 4, Ingredient: "" },
  { name: "Tomate frito", allergic: "", price: 4, Ingredient: "" },
  { name: "Tomate, asado", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Tomate, maduro, pelado y triturado, enlatado",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Tomate, maduro, puré", allergic: "", price: 4, Ingredient: "" },
  { name: "Tomillo, seco", allergic: "", price: 4, Ingredient: "" },
  { name: "Torta de aceite", allergic: "", price: 4, Ingredient: "" },
  { name: "Tortilla, a la francesa", allergic: "", price: 4, Ingredient: "" },
  { name: "Trigo, entero, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Trucha", allergic: "", price: 4, Ingredient: "" },
  { name: "Trucha, ahumada", allergic: "", price: 4, Ingredient: "" },
  { name: "Trufa, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Turrón, tipo Alicante", allergic: "", price: 4, Ingredient: "" },
  { name: "Palmito, en conserva", allergic: "", price: 4, Ingredient: "" },
  { name: "Palometa, cruda", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Palomitas de maíz, sin aceite, sin sal",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pan blanco, de barra", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pan blanco, de barra, sin sal",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pan blanco, de molde, tostado",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pan blanco, frito", allergic: "", price: 4, Ingredient: "" },
  {
    name: 'Pan blanco, tipo "baguette"',
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pan blanco, tostado", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pan blanco, tostado sin sal",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pan de avena", allergic: "", price: 4, Ingredient: "" },
  { name: "Pan de cebada", allergic: "", price: 4, Ingredient: "" },
  { name: "Pan de centeno", allergic: "", price: 4, Ingredient: "" },
  { name: "Pan de leche", allergic: "", price: 4, Ingredient: "" },
  { name: "Pan de maíz", allergic: "", price: 4, Ingredient: "" },
  { name: "Pan integral", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pan integral, de molde, tostado",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pan integral, sin sal", allergic: "", price: 4, Ingredient: "" },
  { name: "Pan integral, tostado", allergic: "", price: 4, Ingredient: "" },
  { name: "Pan rallado", allergic: "", price: 4, Ingredient: "" },
  { name: "Pan tostado integral", allergic: "", price: 4, Ingredient: "" },
  { name: "Pan, tipo hamburguesa", allergic: "", price: 4, Ingredient: "" },
  { name: "Panceta, frita", allergic: "", price: 4, Ingredient: "" },
  { name: "Panga, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Papaya, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Paraguaya", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pasta alimenticia, con huevo, cruda",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pasta alimenticia, con huevo, hervida",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pasta alimenticia, con vegetales, cruda",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pasta alimenticia, cruda", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pasta alimenticia, integral, cruda",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pasta alimenticia, integral, hervida",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pasta alimenticia, rellena con carne, hervida",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pasta de fruta", allergic: "", price: 4, Ingredient: "" },
  { name: "Pasta de sésamo", allergic: "", price: 4, Ingredient: "" },
  { name: "Pastas de te", allergic: "", price: 4, Ingredient: "" },
  { name: "Pastel", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pastel con fruta confitada",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pastel de chocolate", allergic: "", price: 4, Ingredient: "" },
  { name: "Pastel de manzana", allergic: "", price: 4, Ingredient: "" },
  { name: "Patata, asada", allergic: "", price: 4, Ingredient: "" },
  { name: "Patata, cruda", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Patata, frita con aceite s/e, sin sal",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Patata, hervida", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Patata, prefrita, congelada",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Patata, salteada con aceite girasol",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: 'Patatas chips, "lights"', allergic: "", price: 4, Ingredient: "" },
  { name: "Patatas, fritas, chips", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pate de higado de cerdo, 30% de grasa",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Paté de pimienta", allergic: "", price: 4, Ingredient: "" },
  { name: "Pato, entero, asado", allergic: "", price: 4, Ingredient: "" },
  { name: "Pato, entero, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Pavo, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Pavo, fiambre", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pavo, fiambre, bajo en grasa",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pavo, muslo, con piel, crudo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pavo, pechuga, con piel, crudo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pavo, pechuga, sin piel, a la plancha",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pepinillos en vinagre", allergic: "", price: 4, Ingredient: "" },
  { name: "Pepino", allergic: "", price: 4, Ingredient: "" },
  { name: "Pera", allergic: "", price: 4, Ingredient: "" },
  { name: "Pera, enlatada en almíbar", allergic: "", price: 4, Ingredient: "" },
  { name: "Perca, al horno", allergic: "", price: 4, Ingredient: "" },
  { name: "Perca, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Percebe", allergic: "", price: 4, Ingredient: "" },
  { name: "Perdiz, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Perejil, fresco", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pescadilla, congelada, cruda",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pescadilla, rebozada en harina, frita",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pescado, genérico", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Petit líquido, sabor fresa",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Petit suïsse, cereales y fruta",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Petit suisse, chocolate", allergic: "", price: 4, Ingredient: "" },
  { name: "Petit suisse, fresa", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Petit Suisse, natural azucarado",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pez espada, crudo", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pez espada, emperador, plancha",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pichón, sin piel, asado", allergic: "", price: 4, Ingredient: "" },
  { name: "Pijota, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Pimentón, en polvo", allergic: "", price: 4, Ingredient: "" },
  { name: "Pimienta, blanca", allergic: "", price: 4, Ingredient: "" },
  { name: "Pimienta, negra", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pimiento morrón, en conserva",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pimiento rojo, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Pimiento, frito", allergic: "", price: 4, Ingredient: "" },
  { name: "Piña", allergic: "", price: 4, Ingredient: "" },
  { name: "Piña en almíbar", allergic: "", price: 4, Ingredient: "" },
  { name: "Piña, enlatada en su jugo", allergic: "", price: 4, Ingredient: "" },
  { name: "Piñon", allergic: "", price: 4, Ingredient: "" },
  { name: "Piñón, crudo, con cáscara", allergic: "", price: 4, Ingredient: "" },
  { name: "Pipa de calabaza", allergic: "", price: 4, Ingredient: "" },
  { name: "Pipa de girasol", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pipas de girasol, peladas, con sal",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pistacho", allergic: "", price: 4, Ingredient: "" },
  { name: "Pizza, precocinada", allergic: "", price: 4, Ingredient: "" },
  { name: "Plátano", allergic: "", price: 4, Ingredient: "" },
  { name: "Platija, al vapor", allergic: "", price: 4, Ingredient: "" },
  { name: "Platija, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Pollo empanado, frito", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pollo, ala, con piel, cruda",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pollo, entero, con piel, asado",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pollo, entero, con piel, crudo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pollo, fiambre", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pollo, fiambre, bajo en grasa",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pollo, frito", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Pollo, muslo, con piel, asado",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pollo, muslo, con piel, crudo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pollo, parte sin especificar",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Pollo, pechuga, con piel, crudo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pollo, pechuga, plancha", allergic: "", price: 4, Ingredient: "" },
  { name: "Pomelo", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Preparado lácteo con omega 3",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Pudding de pasas", allergic: "", price: 4, Ingredient: "" },
  { name: "Puerro, crudo y congelado", allergic: "", price: 4, Ingredient: "" },
  { name: "Puerro, en conserva", allergic: "", price: 4, Ingredient: "" },
  { name: "Pulmón, de cerdo, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Pulmón, de cordero, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Pulmón, de ternera, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Pulpo", allergic: "", price: 4, Ingredient: "" },
  { name: "Pulpo, hervido", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Puré de patata y queso, en copos",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Puré de patata, con verduras, en copos",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Puré de patata, en copos", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Puré de patatas y champiñones, en copos",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Puré, de patata, con leche",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Bacaladilla", allergic: "", price: 4, Ingredient: "" },
  { name: "Bacalao, ahumado", allergic: "", price: 4, Ingredient: "" },
  { name: "Bacalao, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Bacalao, fresco, al horno", allergic: "", price: 4, Ingredient: "" },
  { name: "Bacalao, frito", allergic: "", price: 4, Ingredient: "" },
  { name: "Bacalao, salado, crudo", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Bacalao, salado, remojado, crudo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Bacón, ahumado, a la parrilla",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Bacon, crudo, con grasa separable",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Bambú, crudo", allergic: "", price: 4, Ingredient: "" },
  {
    name: 'Barra chocolate, tipo "bounty"',
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: 'Barra de chocolate, tipo "Kit-kat"',
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: 'Barra de chocolate, tipo "Mars"',
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Barrita cereales con chocolate",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Barrita cereales con frutas",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Barrita cereales maíz y trigo",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Barrita cereales trigo y chocolate",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Batido de chocolate", allergic: "", price: 4, Ingredient: "" },
  { name: "Batido de fresa", allergic: "", price: 4, Ingredient: "" },
  { name: "Batido de soja", allergic: "", price: 4, Ingredient: "" },
  { name: "Batido fermentado de soja", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Batido lácteo de cacao, bajo en calorías",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Batido lácteo, de fresa, bajo en calorías",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Bebida de soja", allergic: "", price: 4, Ingredient: "" },
  { name: "Bebida energética", allergic: "", price: 4, Ingredient: "" },
  { name: "Bebida isotónica", allergic: "", price: 4, Ingredient: "" },
  { name: "Berberechos", allergic: "", price: 4, Ingredient: "" },
  { name: "Berberechos en conserva", allergic: "", price: 4, Ingredient: "" },
  { name: "Berenjena", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Berenjena, frita, en aceite de girasol",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Berro, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Besugo", allergic: "", price: 4, Ingredient: "" },
  { name: "Bígaro, hervido", allergic: "", price: 4, Ingredient: "" },
  { name: "Bizcocho", allergic: "", price: 4, Ingredient: "" },
  { name: "Bocadillo", allergic: "", price: 4, Ingredient: "" },
  { name: "Bogavante", allergic: "", price: 4, Ingredient: "" },
  { name: "Bogavante, hervido", allergic: "", price: 4, Ingredient: "" },
  { name: "Bollería, genérico", allergic: "", price: 4, Ingredient: "" },
  { name: "Bombón", allergic: "", price: 4, Ingredient: "" },
  { name: "Boniato, crudo", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Bonito del norte, al vapor",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  {
    name: "Bonito del norte, enlatado en aceite de soja",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Bonito en aceite vegetal", allergic: "", price: 4, Ingredient: "" },
  {
    name: "Bonito, enlatado en aceite, escurrido",
    allergic: "",
    price: 4,
    Ingredient: "",
  },
  { name: "Boquerón", allergic: "", price: 4, Ingredient: "" },
  { name: "Boquerón, frito", allergic: "", price: 4, Ingredient: "" },
  { name: "Borraja", allergic: "", price: 4, Ingredient: "" },
  { name: "Breca, cruda", allergic: "", price: 4, Ingredient: "" },
  { name: "Brécol, crudo", allergic: "", price: 4, Ingredient: "" },
  { name: "Brécol, hervido", allergic: "", price: 4, Ingredient: "" },
  { name: "Butifarra", allergic: "", price: 4, Ingredient: "" },
];

async function getRandomProviders() {
  return Provider.aggregate(
    [{ $match: {} }, { $sample: { size: 1 } }],
    (err, docs) => {
      return docs;
    }
  );
}

async function main() {
  const IngredientDocuments = [];
  for (const ingredient of ingredients) {
    const nIngredient = new Ingredient(ingredient);
    const provider = (await getRandomProviders()).map((i) => i._id);
    nIngredient.provider = provider[0];
    nIngredient.allergyc = Math.random() < 0.5;
    nIngredient.price = Math.random() * 10;
    IngredientDocuments.push(nIngredient);
  }
  console.log(
    `Randomly filled ${IngredientDocuments.length}  Ingredients on foods collection`
  );
  const run = async () => {
    const allIngredients = await Ingredient.find();
    if (allIngredients.length > 0) {
      await Ingredient.collection
        .drop()
        .then(() => console.log("Ingredient collection dropped"));
    }
    await Ingredient.insertMany(IngredientDocuments).then(() =>
      console.log(
        "Ingredient collection filled with " +
          IngredientDocuments.length +
          " documents"
      )
    );
    mongoose.disconnect().then(() => console.log("Disconnected"));
  };
  await run();
}
main();
